# Generated by Django 5.2 on 2025-05-02 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company_name', models.CharField(default='미입력 회사', max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('job_type', models.CharField(choices=[('FT', '정규직'), ('PT', '파트타임'), ('CT', '계약직'), ('FR', '프리랜서'), ('IN', '인턴')], default='FT', max_length=2)),
                ('salary', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('skills', models.CharField(blank=True, help_text='예: Python, Django', max_length=200)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
