# Generated by Django 5.2 on 2025-05-02 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='이름없음', max_length=100)),
                ('phone', models.CharField(default='010-0000-0000', max_length=20)),
                ('email', models.EmailField(default='temp@example.com', max_length=254)),
                ('education', models.TextField(blank=True)),
                ('experience', models.TextField(blank=True)),
                ('skills', models.CharField(blank=True, help_text='쉼표로 구분하여 입력 (예: Python, Django, HTML)', max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('portfolio', models.FileField(blank=True, null=True, upload_to='resumes/portfolios/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
