# Generated by Django 5.2 on 2025-05-02 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='career_level',
            field=models.CharField(choices=[('신입', '신입'), ('1-2년차', '1-2년차'), ('3-5년차', '3-5년차'), ('5-10년차', '5-10년차'), ('10년 이상', '10년 이상')], default='신입', max_length=20),
        ),
        migrations.AddField(
            model_name='resume',
            name='employment_type',
            field=models.CharField(choices=[('정규직', '정규직'), ('계약직', '계약직'), ('프리랜서', '프리랜서'), ('인턴', '인턴'), ('기타', '기타')], default='정규직', max_length=20),
        ),
        migrations.AddField(
            model_name='resume',
            name='portfolio_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='preferred_location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='resume',
            name='show_education',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills_detail',
            field=models.TextField(blank=True),
        ),
    ]
